
import styles from "../styles/layoutGlobal.module.scss";

import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "MotorsShop - Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={styles.root}>
            <body className={(inter.className, styles.body)}>{children}</body>
        </html>
    );
}
